#!/bin/bash

nodeunit ExecutorUtilitiesTest.js   
nodeunit FilterBuilderTests.js
nodeunit SchemeManipulationFuncsTests.js
nodeunit SQLParserTests.js  
nodeunit SimpleQueryExecutorTests.js
nodeunit JoinQueryExecutorTests.js                      

