#!/bin/bash

nodeunit ExecutorUtilitiesTest.js   
nodeunit FilterBuilderTests.js
nodeunit SchemeManipulationFuncsTests.js
nodeunit JoinQueryExecutorTests.js
nodeunit SimpleQueryExecutorTests.js
nodeunit SQLParserTests.js                           

