#!/bin/bash

nodeunit ExecutorUtilitiesTests.js
nodeunit FilterBuilderTests.js
nodeunit SchemaManipulationFuncsTests.js
nodeunit SQLParserTests.js  
nodeunit SimpleQueryExecutorTests.js
nodeunit JoinQueryExecutorTests.js                      

